name: Telegram Bot CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'bot/**'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # Optional: Add your bot testing steps here
    # - name: Run Tests
    #   run: |
    #     python -m unittest discover bot/tests
    
    # Note: Actual bot deployment depends on your hosting strategy
    # You might need to add specific deployment steps based on your hosting service